### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by minhnimble** [nkhanh44/Survey_Nimble#11]
Hello Khanh 👋 , thank you for your effort on the code submission. As introduced to you before, I am Mike, Engineering Lead at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions and thus I will create issues where I think there could be more improvements regarding your performance here.

At the same time, please keep in mind that this is a bi-directional process and I would love to hear back from you as well. Therefore, don’t hesitate to raise your questions or share your opinions about the implementation (if any) during the process.

If we are aligned on any issue here and you’d like to correct them, please address the issue using a proper git-flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready) and I will follow up on those fixes. Please note that you don't have to close any of my created issues after merging your PRs, I will help verify and close them for you once they pass. 😇

We expect the code review process to be completed within 2-3 days at most. As a result, ensure you are responsive during this process. If you need additional time, please inform us right away so that we can plan accordingly.

In the end, I really do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by minhnimble** [comment]
Hello Khanh again 👋, I complete my review round at the moment. Please go ahead and provide your feedback on all my proposed issues.

By the way, it is Friday's night now, so have a great weekend! 🌴

**Comment by nkhanh44** [comment]
Hi anh Minh ✌️,
Thanks so much for reviewing my project and pointing out many issues/ cases that i'd not checked for, i really appreciate your support and i will provide feedback on all your proposed issues as soon as i can. :raised_hands:

Happy weekend, anh. :surfer: :dancer:

**Comment by minhnimble** [comment]
Hello, Thieu 👋

I also complete the 2nd round of review just now. Again, you can start providing your feedback on all the new comments and remaining issues at this point.

Have a great afternoon! ☀️

**Comment by minhnimble** [comment]
Good morning, Khanh ☀️

Thank you for your timely updates on the issues! As of this point, my review for this code challenge session reaches a conclusion and thus no more submissions will be needed from your end. For the next step, you will be hearing from the Talent Acquisition team about the decision as soon as possible. 🙏

In the end, it was a good pleasure reviewing your code and getting to know you, you have performed well. 👍 I wish you all the very best. 🍀

**Comment by nkhanh44** [comment]
Afternoon anh Minh 👋 ,

Thank you so much for saying that. I’m delighted to hear it. It was a great pleasure to have you in this review process, i learnt a lot from you here and i really appreciate your support 🙇 .

Best wish for you, anh. 🍀
