### ISSUE TITLE
[Bug] Unit tests build failed issue

### ISSUE THREAD

**Issue by minhnimble** [nkhanh44/Survey_Nimble#12]
## Issue

It is quite nice to see that you've included a few unit tests for multiple View Models of the application. Unfortunately, there is a run test failed issue when I attempted to run them on my Simulator iPhone SE iOS 15.5 with the latest code at the commit c4ae9f42a30e6e0e04c8b21c31dd32fe868225fa.

Here is the screenshot about the error issue:
![Screen Shot 2022-06-24 at 14 29 28](https://user-images.githubusercontent.com/70877098/175486176-632320da-3e38-479e-85f2-c23f163c598c.png)

## Expect

All tests should run successfully without any build failed issue.

## Step to reproduce

1. Run `pod install` to set up the project environments.
2. Open the project with the new `Survey-Nimble.xcworkspace`.
3. Run debug on the project successfully with `Cmd + R`.
4. Run test on the project with `Cmd + U`.
5. Observe the result.

**Comment by nkhanh44** [comment]
Hi anh @minhnimble :v:,
I just fixed this bug via https://github.com/nkhanh44/Survey_Nimble/pull/19, please take a look :blush:
