### ISSUE TITLE
[Question] UI Testing and 3rd-party libraries knowledge concerns 

### ISSUE THREAD

**Issue by minhnimble** [nkhanh44/Survey_Nimble#13]
## Issues

I noticed that you have written the unit tests for the application with a great code coverage percentage, nice work there 👍. At the same time, there are no UI tests found in the application. I am wondering if you ever have the opportunity to write UI tests before? If yes, it would be great if you can demonstrate your skills with a simple UI test to verify some basic UI flows in the application. An example could be the flow to open the Home screen from the Login screen.

Furthermore, I would like to know if you have any experience in any other 3rd-party library for writing unit tests apart from the native XCTest? If yes can you tell me a little bit more about how you would write tests using those libraries?

**Comment by nkhanh44** [comment]
Hello anh ✌️ ,

> But during this review process, after resolving some bug you pointed out, i would like to do my research and add some UI tests.😼

As i said on the comment above, I also added some UITests including some validation and the flow to open the Home screen from the Login screen by using KIF lib that's also recommended in https://nimblehq.co/compass/development/ios/testing/ , please take a look on it :smiley:.

- https://github.com/nkhanh44/Survey_Nimble/pull/24

**Comment by minhnimble** [comment]
It is great to you that you applied the KIF lib for writing UI test. Unfortunately, I don't see you enable the UI test target in the Schema and thus I am not sure how you verify the new UI tests. 🤔

![Screen Shot 2022-06-27 at 13 18 31](https://user-images.githubusercontent.com/70877098/175872390-e02b97c4-5bb1-4217-aa57-ac31b41b8a1b.png)

After enabling it, it looks like your UI tests have some failing problems. Consider taking a look and fix them. 😅

![Screen Shot 2022-06-27 at 13 17 07](https://user-images.githubusercontent.com/70877098/175872497-118624f0-8fcd-4169-b1fa-93a7950d18a9.png)

**Comment by nkhanh44** [comment]
The UITest failed because the conflict among test cases so they were stuck to find AccessibilityLabel 😄 , I added the back function tap for flow test Cases. I also divided them into 2 categories such flowUI test and validation UI test. ✌️ .
I fixed it here:
- https://github.com/nkhanh44/Survey_Nimble/pull/26
