### ISSUE TITLE
[Bug] Starting the app without the internet connection will stuck at the splash screen forever

### ISSUE THREAD

**Issue by minhnimble** [nkhanh44/Survey_Nimble#14]
## Issue

When starting the application without the internet connection, if there is a previous logged session, the user will see the splash screen without any message. Turning the internet connection back online does nothing and the application is stuck there forever.

## Expect

When starting the application without the internet connection, if there is a previous logged session, there should be an option for the user to retry to reload the data instead of blocking the user forever at the splash screen.

## Step to reproduce

https://user-images.githubusercontent.com/70877098/175483794-350b4dc9-fc99-4809-95a9-9f5ec223ae8f.MP4

**Comment by nkhanh44** [comment]
I fixed it in this PR below :sunglasses:
- https://github.com/nkhanh44/Survey_Nimble/pull/22
