### ISSUE TITLE
[Feature] As a user, I see error handling when starting the application without the internet connection

### ISSUE THREAD

**Issue by minhnimble** [nkhanh44/Survey_Nimble#15]
## Issue

Currently, when starting the application freshly without the internet connection, attempting to login or reset password will simply do nothing. As a result, from the user perspective, it can be somewhat confusing on what is the current problem and the users don't know what to do next to resolve the issue.

Attempt to login/reset password with valid credential while the internet is turned off:

https://user-images.githubusercontent.com/70877098/175490647-6c3942bf-a94d-4688-abb1-4d1d222acbfb.MP4

## Expect

The application needs to show an error message for this case to help let the users know how to proceed.

**Comment by nkhanh44** [comment]
Morning anh ✌️ ,
I fixed this bug in this PR below.
- https://github.com/nkhanh44/Survey_Nimble/pull/22
