### ISSUE TITLE
[Bug] The shimmer loading indicator's animation doesn't look identical to the design

### ISSUE THREAD

**Issue by minhnimble** [nkhanh44/Survey_Nimble#16]
## Issue

The application needs to show the initial shimmer loading view with animation after first entering the app with a valid logged in session. Currently, the glow animation for the loading view is a fade in/out animation which is not matching with the design.

## Expect
- The animation for the skeleton loading view must be implemented like the following design with a correct animation that the glow is repeatedly transitioning from the left to the right:

https://user-images.githubusercontent.com/70877098/161499571-fe661524-e7b9-4763-866a-be5aa7564e91.mov

## Step to reproduce:

Open the application with a previously logged in session:

https://user-images.githubusercontent.com/70877098/175492064-062ea140-fcf5-4b8f-a251-935836d2a038.MP4

**Comment by nkhanh44** [comment]
Morning anh, ✌️ 
I fixed this bug using a lib, that's not exactly design but close enough :sweat_smile:.
- https://github.com/nkhanh44/Survey_Nimble/pull/23

**Comment by minhnimble** [comment]
> Thank you for manually adding CLIENT_ID, CLIENT_SECRET before 😹, now it's "automated" 😂 .

No worries, this is a good practice that we should not push secrets on the repository 👍. Pushing the secrets directly to Git is indeed a more convenient option for verification. However, it is not a recommended practice and you should add some comments for letting other people know where to update the secrets 😁
