### ISSUE TITLE
[Bug] The survey images and contents are difficult to see in Home screen

### ISSUE THREAD

**Issue by minhnimble** [nkhanh44/Survey_Nimble#18]
## Issues

There are few UI issues for the survey content in Home screen. I would like to list them out as follow:
- In brighter background images, we would not be able to see the texts clearly as the texts are in white:
   <img src="https://user-images.githubusercontent.com/70877098/175496534-616a21da-4a3f-4217-9b1c-94d09963037e.PNG" width="300">

- The image looks stretched out and is hard to view:
   <img src="https://user-images.githubusercontent.com/70877098/175495795-cadc1077-07d4-4ddc-b49f-287dd4fc6286.PNG" width="300">

- There are weird left and right spaces if the image has a very long height:
   <img src="https://user-images.githubusercontent.com/70877098/175496150-23199577-9e9b-435a-b453-aefdbbac0ce1.jpeg" width="300">

## Expect

The survey content must be clear and properly displayed regardless of the image content like the design.

## Step to reproduce

1. Start the application freshly.
2. Login with valid credential.
3. Swipe to view different surveys in the Home screen.
4. Observe the result.

**Comment by nkhanh44** [comment]
I fixed it in this below PR ✌️ 
ref: https://github.com/nkhanh44/Survey_Nimble/pull/21
