### ISSUE TITLE
[Bug] The page indicator is not updated immediately when scrolling fast in Home screen

### ISSUE THREAD

**Issue by minhnimble** [nkhanh44/Survey_Nimble#25]
## Issue

When swiping through the survey items in Home screen in a quick manner, The page indicator is not updated timely and it is only changed until the users end the scrolling for a brief moment.

## Expect

The page indicator must be updated immediately and timely when users scroll quickly through the survey items in Home screen.

## Step to reproduce

https://user-images.githubusercontent.com/70877098/175875559-c498f8fa-abd2-4146-96b7-391852578fef.MP4

**Comment by nkhanh44** [comment]
> The page indicator must be updated immediately and timely when users scroll quickly through the survey items in Home screen.

I firstly thought it was fine enough for updating the page indicator when scrolling did end even scrolling fast. But you indicated to the idea that `The page indicator must be updated immediately` that is better for UX ✌️ . Learning a lot on this project from you, thanks 😄 .
I updated here:
- https://github.com/nkhanh44/Survey_Nimble/pull/27
